/* Caminho: src/clubes-data.ts
   Objetivo: Lista Mestra Unificada Heart Club 2026 - COMPLETA E CORRIGIDA
*/

export const CLUBS_DATA = [
  // SÉRIE A 2026 (20 CLUBES)
  { api_id: 154, nome: 'Athletico-PR', nome_curto: 'CAP', serie: 'A' },
  { api_id: 1063, nome: 'Atlético-MG', nome_curto: 'CAM', serie: 'A' },
  { api_id: 118, nome: 'Bahia', nome_curto: 'BAH', serie: 'A' },
  { api_id: 120, nome: 'Botafogo', nome_curto: 'BOT', serie: 'A' },
  { api_id: 141, nome: 'Chapecoense', nome_curto: 'CHA', serie: 'A' },
  { api_id: 131, nome: 'Corinthians', nome_curto: 'COR', serie: 'A' },
  { api_id: 138, nome: 'Coritiba', nome_curto: 'CFC', serie: 'A' },
  { api_id: 135, nome: 'Cruzeiro', nome_curto: 'CRU', serie: 'A' },
  { api_id: 127, nome: 'Flamengo', nome_curto: 'FLA', serie: 'A' },
  { api_id: 124, nome: 'Fluminense', nome_curto: 'FLU', serie: 'A' },
  { api_id: 130, nome: 'Grêmio', nome_curto: 'GRE', serie: 'A' },
  { api_id: 119, nome: 'Internacional', nome_curto: 'INT', serie: 'A' },
  { api_id: 1043, nome: 'Mirassol', nome_curto: 'MIR', serie: 'A' },
  { api_id: 121, nome: 'Palmeiras', nome_curto: 'PAL', serie: 'A' },
  { api_id: 140, nome: 'Bragantino', nome_curto: 'BGT', serie: 'A' },
  { api_id: 139, nome: 'Remo', nome_curto: 'REM', serie: 'A' },
  { api_id: 149, nome: 'Santos', nome_curto: 'SAN', serie: 'A' },
  { api_id: 126, nome: 'São Paulo', nome_curto: 'SAO', serie: 'A' },
  { api_id: 133, nome: 'Vasco', nome_curto: 'VAS', serie: 'A' },
  { api_id: 134, nome: 'Vitória', nome_curto: 'VIT', serie: 'A' },

  // SÉRIE B 2026 (20 CLUBES)
  { api_id: 153, nome: 'América-MG', nome_curto: 'AMG', serie: 'B' },
  { api_id: 10065, nome: 'Athletic Club', nome_curto: 'ATH', serie: 'B' },
  { api_id: 1061, nome: 'Atlético-GO', nome_curto: 'ACG', serie: 'B' },
  { api_id: 144, nome: 'Avaí', nome_curto: 'AVA', serie: 'B' },
  { api_id: 1050, nome: 'Botafogo-SP', nome_curto: 'BSP', serie: 'B' },
  { api_id: 148, nome: 'Ceará', nome_curto: 'CEA', serie: 'B' },
  { api_id: 1056, nome: 'CRB', nome_curto: 'CRB', serie: 'B' },
  { api_id: 147, nome: 'Criciúma', nome_curto: 'CRI', serie: 'B' },
  { api_id: 1060, nome: 'Cuiabá', nome_curto: 'CUI', serie: 'B' },
  { api_id: 136, nome: 'Fortaleza', nome_curto: 'FOR', serie: 'B' },
  { api_id: 151, nome: 'Goiás', nome_curto: 'GOI', serie: 'B' },
  { api_id: 142, nome: 'Juventude', nome_curto: 'JUV', serie: 'B' },
  { api_id: 152, nome: 'Londrina', nome_curto: 'LON', serie: 'B' },
  { api_id: 1053, nome: 'Náutico', nome_curto: 'NAU', serie: 'B' },
  { api_id: 1054, nome: 'Novorizontino', nome_curto: 'NOV', serie: 'B' },
  { api_id: 1057, nome: 'Operário-PR', nome_curto: 'OPE', serie: 'B' },
  { api_id: 1052, nome: 'Ponte Preta', nome_curto: 'PON', serie: 'B' },
  { api_id: 1049, nome: 'São Bernardo', nome_curto: 'SBE', serie: 'B' },
  { api_id: 143, nome: 'Sport', nome_curto: 'SPT', serie: 'B' },
  { api_id: 1062, nome: 'Vila Nova', nome_curto: 'VIL', serie: 'B' },

  // SÉRIE C 2026 (20 CLUBES)
  { api_id: 10069, nome: 'Amazonas FC', nome_curto: 'AMA', serie: 'C' },
  { api_id: 150, nome: 'Anápolis', nome_curto: 'ANA', serie: 'C' },
  { api_id: 11033, nome: 'Barra-SC', nome_curto: 'BAR', serie: 'C' },
  { api_id: 1055, nome: 'Botafogo-PB', nome_curto: 'BPB', serie: 'C' },
  { api_id: 1059, nome: 'Brusque', nome_curto: 'BRU', serie: 'C' },
  { api_id: 1011, nome: 'Caxias', nome_curto: 'CAX', serie: 'C' },
  { api_id: 1058, nome: 'Confiança', nome_curto: 'CON', serie: 'C' },
  { api_id: 1046, nome: 'Ferroviária', nome_curto: 'AFE', serie: 'C' },
  { api_id: 145, nome: 'Figueirense', nome_curto: 'FIG', serie: 'C' },
  { api_id: 2541, nome: 'Floresta', nome_curto: 'FLO', serie: 'C' },
  { api_id: 1051, nome: 'Guarani', nome_curto: 'GUA', serie: 'C' },
  { api_id: 1048, nome: 'Inter de Limeira', nome_curto: 'ITL', serie: 'C' },
  { api_id: 11045, nome: 'Itabaiana', nome_curto: 'ITA', serie: 'C' },
  { api_id: 1045, nome: 'Ituano', nome_curto: 'ITU', serie: 'C' },
  { api_id: 10101, nome: 'Maranhão', nome_curto: 'MAC', serie: 'C' },
  { api_id: 10081, nome: 'Maringá', nome_curto: 'MGA', serie: 'C' },
  { api_id: 146, nome: 'Paysandu', nome_curto: 'PAY', serie: 'C' },
  { api_id: 753, nome: 'Santa Cruz', nome_curto: 'STC', serie: 'C' },
  { api_id: 1010, nome: 'Volta Redonda', nome_curto: 'VRE', serie: 'C' },
  { api_id: 1013, nome: 'Ypiranga-RS', nome_curto: 'YPI', serie: 'C' },

  // SÉRIE D 2026 (DESTAQUES)
  { api_id: 1051, nome: 'ABC', nome_curto: 'ABC', serie: 'D' },
  { api_id: 11028, nome: 'ABECAT', nome_curto: 'ABE', serie: 'D' },
  { api_id: 2542, nome: 'Água Santa', nome_curto: 'AGU', serie: 'D' },
  { api_id: 10103, nome: 'Águia de Marabá', nome_curto: 'AGM', serie: 'D' },
  { api_id: 11043, nome: 'Altos', nome_curto: 'ALT', serie: 'D' },
  { api_id: 11049, nome: 'America-RJ', nome_curto: 'ARJ', serie: 'D' },
  { api_id: 10104, nome: 'América-RN', nome_curto: 'ARN', serie: 'D' },
  { api_id: 1064, nome: 'Aparecidense', nome_curto: 'APA', serie: 'D' },
  { api_id: 11050, nome: 'Araguaína', nome_curto: 'ARA', serie: 'D' },
  { api_id: 11046, nome: 'ASA', nome_curto: 'ASA', serie: 'D' },
  { api_id: 11027, nome: 'CRAC', nome_curto: 'CRA', serie: 'D' },
  { api_id: 10105, nome: 'CSA', nome_curto: 'CSA', serie: 'D' },
  { api_id: 10072, nome: 'Gama', nome_curto: 'GAM', serie: 'D' },
  { api_id: 11058, nome: 'Goiatuba', nome_curto: 'GTB', serie: 'D' },
  { api_id: 11022, nome: 'Inhumas', nome_curto: 'INH', serie: 'D' },
  { api_id: 11086, nome: 'Iporá', nome_curto: 'IPO', serie: 'D' },
  { api_id: 11069, nome: 'Retrô', nome_curto: 'RET', serie: 'D' },
  { api_id: 11071, nome: 'Tombense', nome_curto: 'TOM', serie: 'D' },
  { api_id: 11072, nome: 'XV de Piracicaba', nome_curto: 'XVP', serie: 'D' },

  // INTERNACIONAL - EUROPA (50 CLUBES)
  { api_id: 541, nome: 'Real Madrid', nome_curto: 'RMA', serie: 'EUR' },
  { api_id: 529, nome: 'Barcelona', nome_curto: 'BAR', serie: 'EUR' },
  { api_id: 50, nome: 'Manchester City', nome_curto: 'MCI', serie: 'EUR' },
  { api_id: 40, nome: 'Liverpool', nome_curto: 'LIV', serie: 'EUR' },
  { api_id: 157, nome: 'Bayern Munich', nome_curto: 'BAY', serie: 'EUR' },
  { api_id: 33, nome: 'Manchester United', nome_curto: 'MUN', serie: 'EUR' },
  { api_id: 496, nome: 'Juventus', nome_curto: 'JUV', serie: 'EUR' },
  { api_id: 85, nome: 'PSG', nome_curto: 'PSG', serie: 'EUR' },
  { api_id: 492, nome: 'Napoli', nome_curto: 'NAP', serie: 'EUR' },
  { api_id: 505, nome: 'Inter Milan', nome_curto: 'INT', serie: 'EUR' },
  { api_id: 489, nome: 'AC Milan', nome_curto: 'ACM', serie: 'EUR' },
  { api_id: 34, nome: 'Newcastle', nome_curto: 'NEW', serie: 'EUR' },
  { api_id: 42, nome: 'Arsenal', nome_curto: 'ARS', serie: 'EUR' },
  { api_id: 165, nome: 'Dortmund', nome_curto: 'BVB', serie: 'EUR' },
  { api_id: 530, nome: 'Atletico Madrid', nome_curto: 'ATM', serie: 'EUR' },
  { api_id: 197, nome: 'Benfica', nome_curto: 'SLB', serie: 'EUR' },
  { api_id: 211, nome: 'FC Porto', nome_curto: 'FCP', serie: 'EUR' },
  { api_id: 173, nome: 'RB Leipzig', nome_curto: 'RBL', serie: 'EUR' },
  { api_id: 168, nome: 'Bayer Leverkusen', nome_curto: 'B04', serie: 'EUR' },
  { api_id: 611, nome: 'Ajax', nome_curto: 'AJX', serie: 'EUR' },
  { api_id: 47, nome: 'Tottenham', nome_curto: 'TOT', serie: 'EUR' },
  { api_id: 49, nome: 'Chelsea', nome_curto: 'CHE', serie: 'EUR' },
  { api_id: 521, nome: 'AS Roma', nome_curto: 'ROM', serie: 'EUR' },
  { api_id: 497, nome: 'Lazio', nome_curto: 'LAZ', serie: 'EUR' },
  { api_id: 502, nome: 'Fiorentina', nome_curto: 'FIO', serie: 'EUR' },
  { api_id: 499, nome: 'Atalanta', nome_curto: 'ATA', serie: 'EUR' },
  { api_id: 536, nome: 'Sevilla', nome_curto: 'SEV', serie: 'EUR' },
  { api_id: 540, nome: 'Villarreal', nome_curto: 'VIL', serie: 'EUR' },
  { api_id: 532, nome: 'Valencia', nome_curto: 'VAL', serie: 'EUR' },
  { api_id: 531, nome: 'Athletic Bilbao', nome_curto: 'ATH', serie: 'EUR' },
  { api_id: 161, nome: 'Wolfsburg', nome_curto: 'WOL', serie: 'EUR' },
  { api_id: 159, nome: 'Hertha Berlin', nome_curto: 'BSC', serie: 'EUR' },
  { api_id: 81, nome: 'Marseille', nome_curto: 'OM', serie: 'EUR' },
  { api_id: 79, nome: 'Lille', nome_curto: 'LOSC', serie: 'EUR' },
  { api_id: 91, nome: 'Monaco', nome_curto: 'ASM', serie: 'EUR' },
  { api_id: 94, nome: 'Rennes', nome_curto: 'REN', serie: 'EUR' },
  { api_id: 212, nome: 'Sporting CP', nome_curto: 'SCP', serie: 'EUR' },
  { api_id: 210, nome: 'Braga', nome_curto: 'SCB', serie: 'EUR' },
  { api_id: 194, nome: 'Feyenoord', nome_curto: 'FEY', serie: 'EUR' },
  { api_id: 195, nome: 'PSV Eindhoven', nome_curto: 'PSV', serie: 'EUR' },
  { api_id: 247, nome: 'Celtic', nome_curto: 'CEL', serie: 'EUR' },
  { api_id: 252, nome: 'Rangers', nome_curto: 'RAN', serie: 'EUR' },
  { api_id: 328, nome: 'Galatasaray', nome_curto: 'GAL', serie: 'EUR' },
  { api_id: 327, nome: 'Fenerbahce', nome_curto: 'FEN', serie: 'EUR' },
  { api_id: 329, nome: 'Besiktas', nome_curto: 'BES', serie: 'EUR' },
  { api_id: 550, nome: 'Shakhtar Donetsk', nome_curto: 'SHA', serie: 'EUR' },
  { api_id: 551, nome: 'Dynamo Kyiv', nome_curto: 'DKV', serie: 'EUR' },
  { api_id: 231, nome: 'Olympiakos', nome_curto: 'OLY', serie: 'EUR' },
  { api_id: 232, nome: 'Panathinaikos', nome_curto: 'PAN', serie: 'EUR' },
  { api_id: 234, nome: 'PAOK', nome_curto: 'PAO', serie: 'EUR' },

  // INTERNACIONAL - AMÉRICA DO SUL (30 CLUBES)
  { api_id: 441, nome: 'Boca Juniors', nome_curto: 'BOC', serie: 'INT' },
  { api_id: 442, nome: 'River Plate', nome_curto: 'RIV', serie: 'INT' },
  { api_id: 268, nome: 'Peñarol', nome_curto: 'PEN', serie: 'INT' },
  { api_id: 272, nome: 'Olimpia', nome_curto: 'OLI', serie: 'INT' },
  { api_id: 451, nome: 'Atlético Nacional', nome_curto: 'ATN', serie: 'INT' },
  { api_id: 273, nome: 'Libertad', nome_curto: 'LIB', serie: 'INT' },
  { api_id: 445, nome: 'Racing Club', nome_curto: 'RAC', serie: 'INT' },
  { api_id: 449, nome: 'Independiente', nome_curto: 'IND', serie: 'INT' },
  { api_id: 269, nome: 'Nacional-URU', nome_curto: 'NAC', serie: 'INT' },
  { api_id: 450, nome: 'San Lorenzo', nome_curto: 'SLO', serie: 'INT' },
  { api_id: 455, nome: 'Colo-Colo', nome_curto: 'CC', serie: 'INT' },
  { api_id: 1121, nome: 'Ind. del Valle', nome_curto: 'IDV', serie: 'INT' },
  { api_id: 1122, nome: 'LDU Quito', nome_curto: 'LDU', serie: 'INT' },
  { api_id: 1123, nome: 'Barcelona-EQU', nome_curto: 'BSC', serie: 'INT' },
  { api_id: 1124, nome: 'Cerro Porteño', nome_curto: 'CCP', serie: 'INT' },
  { api_id: 1125, nome: 'Estudiantes', nome_curto: 'EST', serie: 'INT' },
  { api_id: 1126, nome: 'Vélez Sarsfield', nome_curto: 'VEL', serie: 'INT' },
  { api_id: 1127, nome: 'U. de Chile', nome_curto: 'UCH', serie: 'INT' },
  { api_id: 1128, nome: 'U. Católica', nome_curto: 'UCA', serie: 'INT' },
  { api_id: 1129, nome: 'Alianza Lima', nome_curto: 'ALI', serie: 'INT' },
  { api_id: 1130, nome: 'Universitario', nome_curto: 'UNI', serie: 'INT' },
  { api_id: 1131, nome: 'Bolívar', nome_curto: 'BOL', serie: 'INT' },
  { api_id: 1132, nome: 'The Strongest', nome_curto: 'STR', serie: 'INT' },
  { api_id: 1133, nome: 'Millonarios', nome_curto: 'MIL', serie: 'INT' },
  { api_id: 1134, nome: 'Junior Barranquilla', nome_curto: 'JUN', serie: 'INT' },
  { api_id: 1135, nome: 'Caracas FC', nome_curto: 'CFC', serie: 'INT' },
  { api_id: 1136, nome: 'Dep. Táchira', nome_curto: 'TAC', serie: 'INT' },
  { api_id: 1137, nome: 'Melgar', nome_curto: 'MEL', serie: 'INT' },
  { api_id: 1138, nome: 'Defensor Sporting', nome_curto: 'DEF', serie: 'INT' },
  { api_id: 1139, nome: 'Emelec', nome_curto: 'EME', serie: 'INT' }
];