// Caminho/Arquivo: src/clubes-data.ts
export interface ClubData {
  nome: string;
  nome_curto: string;
  serie: string;
  cidade: string;
  estado: string;
  pais: string;
  mascote: string;
  logoUrl: string;
}

const getLogoUrl = (nome: string, cidade: string, estado: string, pais: string): string => {
  const normalize = (str: string) =>
    str.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
  
  const overrides: Record<string, string> = {
    "Vila Nova": "vila-nova-goiania-go-brasil",
    "Atlético-MG": "atletico-mg-belo-horizonte-mg-brasil",
    "Goiás": "goias-goiania-go-brasil",
    "Atlético-GO": "atletico-go-goiania-go-brasil",
    "Santos": "santos-santos-sp-brasil",
    "Athletico-PR": "athletico-pr-curitiba-pr-brasil",
    "Bayern Munich": "bayern-munich-munique-baviera-alemanha",
    "Bayer 04 Leverkusen": "bayer-04-leverkusen-leverkusen-germany-alemanha",
    "Borussia Dortmund": "borussia-dortmund-dortmund-rhenania-alemanha",
    "Paris Saint-Germain": "paris-saint-germain-paris-paris-franca",
    "Tottenham Hotspur": "tottenham-hotspur-londres-londres-inglaterra",
    "Manchester United": "manchester-united-manchester-england-inglaterra"
  };

  const slug = overrides[nome] || `${normalize(nome)}-${normalize(cidade)}-${normalize(estado)}-${normalize(pais)}`;
  return `/logos/${slug}.png`;
};

const RAW_CLUBS: Omit<ClubData, 'logoUrl'>[] = [
  { nome: 'Aberdeen', nome_curto: 'ABE', serie: 'INT', cidade: 'Aberdeen', estado: 'Escócia', pais: 'Escócia', mascote: 'The Dons' },
  { nome: 'AC Milan', nome_curto: 'MIL', serie: 'INT', cidade: 'Milão', estado: 'Lombardia', pais: 'Itália', mascote: 'Milanello' },
  { nome: 'Ajax', nome_curto: 'AJX', serie: 'INT', cidade: 'Amsterdã', estado: 'Holanda do Norte', pais: 'Holanda', mascote: 'Lucky Lynx' },
  { nome: 'Al Masry', nome_curto: 'ALM', serie: 'INT', cidade: 'Port Said', estado: 'Egypt', pais: 'Egito', mascote: 'Águia Verde' },
  { nome: 'Amanat Baghdad SC', nome_curto: 'AMN', serie: 'INT', cidade: 'Baghdad', estado: 'Iraq', pais: 'Iraque', mascote: 'Leão da Babilônia' },
  { nome: 'América de Cali', nome_curto: 'AME', serie: 'INT', cidade: 'Cali', estado: 'Colômbia', pais: 'Colômbia', mascote: 'Diabo Vermelho' },
  { nome: 'Anápolis FC', nome_curto: 'ANA', serie: 'D', cidade: 'Anápolis', estado: 'Brazil', pais: 'Brasil', mascote: 'Galo da Comarca' },
  { nome: 'Ankaragücü', nome_curto: 'ANK', serie: 'INT', cidade: 'Ankara', estado: 'Turkey', pais: 'Turquia', mascote: 'Galo' },
  { nome: 'Aris Thessaloniki', nome_curto: 'ARI', serie: 'INT', cidade: 'Thessaloniki', estado: 'Greece', pais: 'Grécia', mascote: 'Deus Ares' },
  { nome: 'Arsenal', nome_curto: 'ARS', serie: 'INT', cidade: 'Londres', estado: 'Londres', pais: 'Inglaterra', mascote: 'Gunnersaurus' },
  { nome: 'AS Monaco', nome_curto: 'MON', serie: 'INT', cidade: 'Monaco', estado: 'Monaco', pais: 'Monaco', mascote: 'Bouba' },
  { nome: 'Aswan SC', nome_curto: 'ASW', serie: 'INT', cidade: 'Aswan', estado: 'Egypt', pais: 'Egito', mascote: 'Crocodilo' },
  { nome: 'Atalanta', nome_curto: 'ATA', serie: 'INT', cidade: 'Bergamo', estado: 'Italy', pais: 'Itália', mascote: 'Deusa Atalanta' },
  { nome: 'Athletic Bilbao', nome_curto: 'ATH', serie: 'INT', cidade: 'Bilbao', estado: 'Spain', pais: 'Espanha', mascote: 'Leão' },
  { nome: 'Athletico-PR', nome_curto: 'CAP', serie: 'A', cidade: 'Curitiba', estado: 'PR', pais: 'Brasil', mascote: 'Furacão' },
  { nome: 'Atlético Bucaramanga', nome_curto: 'BUC', serie: 'INT', cidade: 'Bucaramanga', estado: 'Colombia', pais: 'Colômbia', mascote: 'Leopardo' },
  { nome: 'Atlético-GO', nome_curto: 'ACG', serie: 'B', cidade: 'Goiania', estado: 'GO', pais: 'Brasil', mascote: 'Dragão' },
  { nome: 'Atlético Huila', nome_curto: 'HUI', serie: 'INT', cidade: 'Neiva', estado: 'Colombia', pais: 'Colômbia', mascote: 'Opita' },
  { nome: 'Atlético Madrid', nome_curto: 'ATM', serie: 'INT', cidade: 'Madrid', estado: 'Spain', pais: 'Espanha', mascote: 'Indi' },
  { nome: 'Atlético-MG', nome_curto: 'CAM', serie: 'A', cidade: 'Belo Horizonte', estado: 'MG', pais: 'Brasil', mascote: 'Galo' },
  { nome: 'Atlético Nacional', nome_curto: 'NAC', serie: 'INT', cidade: 'Medellin', estado: 'Colombia', pais: 'Colômbia', mascote: 'Nacho' },
  { nome: 'Atlético Platense', serie: 'INT', nome_curto: 'PLA', cidade: 'Vicente Lopez', estado: 'Argentina', pais: 'Argentina', mascote: 'Calamar' },
  { nome: 'Avaí', nome_curto: 'AVA', serie: 'B', cidade: 'Florianopolis', estado: 'SC', pais: 'Brasil', mascote: 'Leão da Ilha' },
  { nome: 'Ayacucho FC', nome_curto: 'AYA', serie: 'INT', cidade: 'Ayacucho', estado: 'Peru', pais: 'Peru', mascote: 'Raposa' },
  { nome: 'Bahia', nome_curto: 'BAH', serie: 'A', cidade: 'Salvador', estado: 'BA', pais: 'Brasil', mascote: 'Super-Homem' },
  { nome: 'Banfield', nome_curto: 'BAN', serie: 'INT', cidade: 'Banfield', estado: 'Argentina', pais: 'Argentina', mascote: 'Taladro' },
  { nome: 'Barcelona', nome_curto: 'FCB', serie: 'INT', cidade: 'Barcelona', estado: 'Catalunha', pais: 'Espanha', mascote: 'Culê' },
  { nome: 'Bayer 04 Leverkusen', nome_curto: 'B04', serie: 'INT', cidade: 'Leverkusen', estado: 'Germany', pais: 'Alemanha', mascote: 'Brian the Lion' },
  { nome: 'Bayern Munich', nome_curto: 'BAY', serie: 'INT', cidade: 'Munique', estado: 'Baviera', pais: 'Alemanha', mascote: 'Berni' },
  { nome: 'Benfica', nome_curto: 'SLB', serie: 'INT', cidade: 'Lisboa', estado: 'Lisboa', pais: 'Portugal', mascote: 'Vitória' },
  { nome: 'Boa Esporte', nome_curto: 'BOA', serie: 'D', cidade: 'Varginha', estado: 'MG', pais: 'Brasil', mascote: 'Coruja' },
  { nome: 'Boca Juniors', nome_curto: 'BOC', serie: 'INT', cidade: 'Buenos Aires', estado: 'Buenos Aires', pais: 'Argentina', mascote: 'Xeneize' },
  { nome: 'Bodo Glimt', nome_curto: 'BOD', serie: 'INT', cidade: 'Bodo', estado: 'Norway', pais: 'Noruega', mascote: 'Escova de Dente' },
  { nome: 'Borussia Dortmund', nome_curto: 'BVB', serie: 'INT', cidade: 'Dortmund', estado: 'Rhenania', pais: 'Alemanha', mascote: 'Emma' },
  { nome: 'Botafogo', nome_curto: 'BOT', serie: 'A', cidade: 'Rio de Janeiro', estado: 'RJ', pais: 'Brasil', mascote: 'Manequinho' },
  { nome: 'Boyaca Chico', nome_curto: 'BOY', serie: 'INT', cidade: 'Tunja', estado: 'Colombia', pais: 'Colômbia', mascote: 'Xadrez' },
  { nome: 'Brasil de Pelotas', nome_curto: 'GEB', serie: 'D', cidade: 'Pelotas', estado: 'RS', pais: 'Brasil', mascote: 'Xavante' },
  { nome: 'Burundi National Team', nome_curto: 'BUR', serie: 'SEL', cidade: 'Bujumbura', estado: 'Burundi', pais: 'Burundi', mascote: 'Andorinhas' },
  { nome: 'CD Juventud Unida', nome_curto: 'JUV', serie: 'INT', cidade: 'Gualeguaychu', estado: 'Argentina', pais: 'Argentina', mascote: 'Leão' },
  { nome: 'CD Platense', nome_curto: 'PLA', serie: 'INT', cidade: 'Zacatecoluca', estado: 'El Salvador', pais: 'El Salvador', mascote: 'Galo' },
  { nome: 'CD Vida', nome_curto: 'VID', serie: 'INT', cidade: 'La Ceiba', estado: 'Honduras', pais: 'Honduras', mascote: 'Cocotero' },
  { nome: 'Celtic', nome_curto: 'CEL', serie: 'INT', cidade: 'Glasgow', estado: 'Escocia', pais: 'Escocia', mascote: 'Hoopy the Hound' },
  { nome: 'Chelsea', nome_curto: 'CHE', serie: 'INT', cidade: 'Londres', estado: 'Londres', pais: 'Inglaterra', mascote: 'Stamford the Lion' },
  { nome: 'Copa Americana', nome_curto: 'COP', serie: 'INT', cidade: 'Miami', estado: 'USA', pais: 'Estados Unidos', mascote: 'Águia' },
  { nome: 'Corinthians', nome_curto: 'COR', serie: 'A', cidade: 'Sao Paulo', estado: 'SP', pais: 'Brasil', mascote: 'Mosqueteiro' },
  { nome: 'Coritiba', nome_curto: 'CFC', serie: 'B', cidade: 'Curitiba', estado: 'PR', pais: 'Brasil', mascote: 'Vovô Coxa' },
  { nome: 'CRB', nome_curto: 'CRB', serie: 'B', cidade: 'Maceio', estado: 'AL', pais: 'Brasil', mascote: 'Galo de Campina' },
  { nome: 'Criciuma', nome_curto: 'CRI', serie: 'A', cidade: 'Criciuma', estado: 'SC', pais: 'Brasil', mascote: 'Tigre' },
  { nome: 'Cruzeiro', nome_curto: 'CRU', serie: 'A', cidade: 'Belo Horizonte', estado: 'MG', pais: 'Brasil', mascote: 'Raposa' },
  { nome: 'Defensa y Justicia', nome_curto: 'DYJ', serie: 'INT', cidade: 'Florencio Varela', estado: 'Argentina', pais: 'Argentina', mascote: 'Falcão' },
  { nome: 'Deportivo Cali', nome_curto: 'CAL', serie: 'INT', cidade: 'Cali', estado: 'Colombia', pais: 'Colômbia', mascote: 'Verdiblanco' },
  { nome: 'Deportivo Independiente Medellin', nome_curto: 'DIM', serie: 'INT', cidade: 'Medellin', estado: 'Colombia', pais: 'Colômbia', mascote: 'Poderoso' },
  { nome: 'Deportivo Pasto', nome_curto: 'PAS', serie: 'INT', cidade: 'Pasto', estado: 'Colombia', pais: 'Colômbia', mascote: 'Vulcão' },
  { nome: 'Egypt National Team', nome_curto: 'EGY', serie: 'SEL', cidade: 'Cairo', estado: 'Egypt', pais: 'Egito', mascote: 'Faraós' },
  { nome: 'El Entag El Harby', nome_curto: 'ENT', serie: 'INT', cidade: 'Cairo', estado: 'Egypt', pais: 'Egito', mascote: 'Engenheiros' },
  { nome: 'Envigado', nome_curto: 'ENV', serie: 'INT', cidade: 'Envigado', estado: 'Colombia', pais: 'Colômbia', mascote: 'Laranja' },
  { nome: 'Espanyol', nome_curto: 'ESP', serie: 'INT', cidade: 'Barcelona', estado: 'Spain', pais: 'Espanha', mascote: 'Periquito' },
  { nome: 'Estudiantes', nome_curto: 'EST', serie: 'INT', cidade: 'La Plata', estado: 'Argentina', pais: 'Argentina', mascote: 'Leon' },
  { nome: 'Eswatini National Team', nome_curto: 'ESW', serie: 'SEL', cidade: 'Lobamba', estado: 'Eswatini', pais: 'Esuatini', mascote: 'Escudo Real' },
  { nome: 'Farense', nome_curto: 'FAR', serie: 'INT', cidade: 'Faro', estado: 'Portugal', pais: 'Portugal', mascote: 'Leão de Faro' },
  { nome: 'FC Davis', nome_curto: 'DAV', serie: 'INT', cidade: 'Davis', estado: 'USA', pais: 'Estados Unidos', mascote: 'Leão' },
  { nome: 'Fenerbahce', nome_curto: 'FEN', serie: 'INT', cidade: 'Istambul', estado: 'Istambul', pais: 'Turquia', mascote: 'Canário Amarelo' },
  { nome: 'Fiorentina', nome_curto: 'FIO', serie: 'INT', cidade: 'Florence', estado: 'Italy', pais: 'Itália', mascote: 'Grifone' },
  { nome: 'Fjolnir', nome_curto: 'FJO', serie: 'INT', cidade: 'Reykjavik', estado: 'Iceland', pais: 'Islândia', mascote: 'Viking' },
  { nome: 'FK Jablonec', nome_curto: 'JAB', serie: 'INT', cidade: 'Jablonec nad Nisou', estado: 'Czech Republic', pais: 'Republica Tcheca', mascote: 'Galax' },
  { nome: 'Flamengo', nome_curto: 'FLA', serie: 'A', cidade: 'Rio de Janeiro', estado: 'RJ', pais: 'Brasil', mascote: 'Urubu' },
  { nome: 'Fluminense', nome_curto: 'FLU', serie: 'A', cidade: 'Rio de Janeiro', estado: 'RJ', pais: 'Brasil', mascote: 'Guerreirinho' },
  { nome: 'Fortaleza', nome_curto: 'FOR', serie: 'A', cidade: 'Fortaleza', estado: 'CE', pais: 'Brasil', mascote: 'Leão' },
  { nome: 'Goiás', nome_curto: 'GOI', serie: 'B', cidade: 'Goiania', estado: 'GO', pais: 'Brasil', mascote: 'Periquito' },
  { nome: 'Gomo FC', nome_curto: 'GOM', serie: 'INT', cidade: 'Atlanta', estado: 'USA', pais: 'Estados Unidos', mascote: 'Gomo' },
  { nome: 'Grasshopper', nome_curto: 'GRA', serie: 'INT', cidade: 'Zurich', estado: 'Switzerland', pais: 'Suica', mascote: 'Gafanhoto' },
  { nome: 'Gremio', nome_curto: 'GRE', serie: 'A', cidade: 'Porto Alegre', estado: 'RS', pais: 'Brasil', mascote: 'Mosqueteiro' },
  { nome: 'Guarani', nome_curto: 'GUA', serie: 'B', cidade: 'Campinas', estado: 'SP', pais: 'Brasil', mascote: 'Bugre' },
  { nome: 'Guinea-Bissau National Team', nome_curto: 'GBS', serie: 'SEL', cidade: 'Bissau', estado: 'Guinea-Bissau', pais: 'Guine Bissau', mascote: 'Djurtus' },
  { nome: 'Haugesund', nome_curto: 'HAU', serie: 'INT', cidade: 'Haugesund', estado: 'Norway', pais: 'Noruega', mascote: 'Gaivota' },
  { nome: 'Heerenveen', nome_curto: 'HEE', serie: 'INT', cidade: 'Heerenveen', estado: 'Netherlands', pais: 'Holanda', mascote: 'Heero' },
  { nome: 'Hertha Berlim', nome_curto: 'BSC', serie: 'INT', cidade: 'Berlim', estado: 'Berlim', pais: 'Alemanha', mascote: 'Herthinho' },
  { nome: 'Honduras Progreso', nome_curto: 'HPR', serie: 'INT', cidade: 'El Progreso', estado: 'Honduras', pais: 'Honduras', mascote: 'Ribeirinho' },
  { nome: 'Huracan', nome_curto: 'HUR', serie: 'INT', cidade: 'Buenos Aires', estado: 'Argentina', pais: 'Argentina', mascote: 'Globo' },
  { nome: 'IBV', nome_curto: 'IBV', serie: 'INT', cidade: 'Vestmannaeyjar', estado: 'Iceland', pais: 'Islândia', mascote: 'Puffin' },
  { nome: 'Independiente Santa Fe', nome_curto: 'SFE', serie: 'INT', cidade: 'Bogota', estado: 'Colombia', pais: 'Colômbia', mascote: 'Leão' },
  { nome: 'Inter Milan', nome_curto: 'INT', serie: 'INT', cidade: 'Milão', estado: 'Lombardia', pais: 'Itália', mascote: 'Biscione' },
  { nome: 'Internacional FC de Palmira', nome_curto: 'INP', serie: 'INT', cidade: 'Palmira', estado: 'Colombia', pais: 'Colômbia', mascote: 'Leão' },
  { nome: 'Internacional', nome_curto: 'INT', serie: 'A', cidade: 'Porto Alegre', estado: 'RS', pais: 'Brasil', mascote: 'Saci' },
  { nome: 'Ituano', nome_curto: 'ITU', serie: 'B', cidade: 'Itu', estado: 'SP', pais: 'Brasil', mascote: 'Galo' },
  { nome: 'Jaguares de Cordoba', nome_curto: 'JAG', serie: 'INT', cidade: 'Monteria', estado: 'Colombia', pais: 'Colômbia', mascote: 'Jaguar' },
  { nome: 'Junior Barranquilla', nome_curto: 'JUN', serie: 'INT', cidade: 'Barranquilla', estado: 'Colombia', pais: 'Colômbia', mascote: 'Tiburón' },
  { nome: 'Juticalpa FC', nome_curto: 'JUT', serie: 'INT', cidade: 'Juticalpa', estado: 'Honduras', pais: 'Honduras', mascote: 'Canecheros' },
  { nome: 'Juventude', nome_curto: 'JUV', serie: 'A', cidade: 'Caxias do Sul', estado: 'RS', pais: 'Brasil', mascote: 'Papo' },
  { nome: 'Juventus', nome_curto: 'JUV', serie: 'INT', cidade: 'Turim', estado: 'Piemonte', pais: 'Itália', mascote: 'Zebra' },
  { nome: 'KA Akureyri', nome_curto: 'KAA', serie: 'INT', cidade: 'Akureyri', estado: 'Iceland', pais: 'Islândia', mascote: 'Guerreiro' },
  { nome: 'Keflavik', nome_curto: 'KEF', serie: 'INT', cidade: 'Keflavik', estado: 'Iceland', pais: 'Islândia', mascote: 'Gigante' },
  { nome: 'Kocaeli Birlikspor', nome_curto: 'KOC', serie: 'INT', cidade: 'Korfez', estado: 'Turkey', pais: 'Turquia', mascote: 'Cavaleiro' },
  { nome: 'Leon Huanuco', nome_curto: 'LEO', serie: 'INT', cidade: 'Huanuco', estado: 'Peru', pais: 'Peru', mascote: 'Leão' },
  { nome: 'Lille', nome_curto: 'LIL', serie: 'INT', cidade: 'Lille', estado: 'Nord', pais: 'Franca', mascote: 'Dogue' },
  { nome: 'Liverpool', nome_curto: 'LIV', serie: 'INT', cidade: 'Liverpool', estado: 'Merseyside', pais: 'Inglaterra', mascote: 'Mighty Red' },
  { nome: 'Lobos UPNFM', nome_curto: 'LOB', serie: 'INT', cidade: 'Tegucigalpa', estado: 'Honduras', pais: 'Honduras', mascote: 'Lobo' },
  { nome: 'Londrina', nome_curto: 'LEC', serie: 'C', cidade: 'Londrina', estado: 'PR', pais: 'Brasil', mascote: 'Tubarão' },
  { nome: 'Manchester City', nome_curto: 'MCI', serie: 'INT', cidade: 'Manchester', estado: 'Manchester', pais: 'Inglaterra', mascote: 'Moonchester' },
  { nome: 'Manchester United', nome_curto: 'MUN', serie: 'INT', cidade: 'Manchester', estado: 'England', pais: 'Inglaterra', mascote: 'Fred the Red' },
  { nome: 'Millonarios', nome_curto: 'MIL', serie: 'INT', cidade: 'Bogota', estado: 'Colombia', pais: 'Colômbia', mascote: 'Embaixador' },
  { nome: 'Minneapolis City SC', nome_curto: 'MIN', serie: 'INT', cidade: 'Minneapolis', estado: 'USA', pais: 'Estados Unidos', mascote: 'Corvo' },
  { nome: 'Molde', nome_curto: 'MOL', serie: 'INT', cidade: 'Molde', estado: 'Noruega', pais: 'Noruega', mascote: 'Águia' },
  { nome: 'Motagua', nome_curto: 'MOT', serie: 'INT', cidade: 'Tegucigalpa', estado: 'Honduras', pais: 'Honduras', mascote: 'Águia' },
  { nome: 'Naft Al-Janoob SC', nome_curto: 'NAF', serie: 'INT', cidade: 'Basra', estado: 'Iraq', pais: 'Iraque', mascote: 'Petroleiro' },
  { nome: 'Naft Al-Wasat SC', nome_curto: 'WAS', serie: 'INT', cidade: 'Najaf', estado: 'Iraq', pais: 'Iraque', mascote: 'Rouxinol' },
  { nome: 'Napoli', nome_curto: 'NAP', serie: 'INT', cidade: 'Napoles', estado: 'Campania', pais: 'Itália', mascote: 'Burro' },
  { nome: 'Newcastle United', nome_curto: 'NEW', serie: 'INT', cidade: 'Newcastle', estado: 'Inglaterra', pais: 'Inglaterra', mascote: 'Pega' },
  { nome: 'Newtown Pride FC', nome_curto: 'NEW', serie: 'INT', cidade: 'Newtown', estado: 'USA', pais: 'Estados Unidos', mascote: 'Orgulho' },
  { nome: 'OFI Crete', nome_curto: 'OFI', serie: 'INT', cidade: 'Heraklion', estado: 'Greece', pais: 'Grécia', mascote: 'Cobra' },
  { nome: 'Olimpia', nome_curto: 'OLI', serie: 'INT', cidade: 'Asuncion', estado: 'Paraguay', pais: 'Paraguai', mascote: 'Rei' },
  { nome: 'Olympique Marseille', nome_curto: 'OM', serie: 'INT', cidade: 'Marselha', estado: 'Provenca', pais: 'Franca', mascote: 'Sardinha' },
  { nome: 'Once Caldas', nome_curto: 'ONC', serie: 'INT', cidade: 'Manizales', estado: 'Colombia', pais: 'Colômbia', mascote: 'Branco' },
  { nome: 'Pacos de Ferreira', nome_curto: 'PAC', serie: 'INT', cidade: 'Pacos de Ferreira', estado: 'Portugal', pais: 'Portugal', mascote: 'Castor' },
  { nome: 'Palmeiras', nome_curto: 'PAL', serie: 'A', cidade: 'Sao Paulo', estado: 'SP', pais: 'Brasil', mascote: 'Periquito' },
  { nome: 'Paris Saint-Germain', nome_curto: 'PSG', serie: 'INT', cidade: 'Paris', estado: 'Paris', pais: 'Franca', mascote: 'Germain' },
  { nome: 'Paysandu', nome_curto: 'PAY', serie: 'B', cidade: 'Belem', estado: 'PA', pais: 'Brasil', mascote: 'Lobo' },
  { nome: 'Peoria City', nome_curto: 'PEO', serie: 'INT', cidade: 'Peoria', estado: 'USA', pais: 'Estados Unidos', mascote: 'Cidade' },
  { nome: 'Ponte Preta', nome_curto: 'PON', serie: 'B', cidade: 'Campinas', estado: 'SP', pais: 'Brasil', mascote: 'Macaca' },
  { nome: 'Porto', nome_curto: 'FCP', serie: 'INT', cidade: 'Porto', estado: 'Porto', pais: 'Portugal', mascote: 'Dragão' },
  { nome: 'PSV Eindhoven', nome_curto: 'PSV', serie: 'INT', cidade: 'Eindhoven', estado: 'Brabante', pais: 'Holanda', mascote: 'Phoxy' },
  { nome: 'RB Leipzig', nome_curto: 'RBL', serie: 'INT', cidade: 'Leipzig', estado: 'Saxonia', pais: 'Alemanha', mascote: 'Bulli' },
  { nome: 'Real Espana', nome_curto: 'RES', serie: 'INT', cidade: 'San Pedro Sula', estado: 'Honduras', pais: 'Honduras', mascote: 'Realeza' },
  { nome: 'Real Madrid', nome_curto: 'RMA', serie: 'INT', cidade: 'Madrid', estado: 'Madrid', pais: 'Espanha', mascote: 'Real' },
  { nome: 'Roma', nome_curto: 'ROM', serie: 'INT', cidade: 'Roma', estado: 'Lazio', pais: 'Itália', mascote: 'Romolo' },
  { nome: 'Saint-Etienne', nome_curto: 'STE', serie: 'INT', cidade: 'Saint-Etienne', estado: 'France', pais: 'Franca', mascote: 'Pantil' },
  { nome: 'Santa Cruz', nome_curto: 'SCZ', serie: 'D', cidade: 'Recife', estado: 'PE', pais: 'Brasil', mascote: 'Cobra Coral' },
  { nome: 'Sao Paulo', nome_curto: 'SAO', serie: 'A', cidade: 'Sao Paulo', estado: 'SP', pais: 'Brasil', mascote: 'Santo' },
  { nome: 'Sevilla', nome_curto: 'SEV', serie: 'INT', cidade: 'Seville', estado: 'Spain', pais: 'Espanha', mascote: 'Sevillano' },
  { nome: 'Shakhtar Donetsk', nome_curto: 'SHA', serie: 'INT', cidade: 'Donetsk', estado: 'Ukraine', pais: 'Ucrania', mascote: 'Mineiro' },
  { nome: 'Social Sol', nome_curto: 'SOC', serie: 'INT', cidade: 'Olanchito', estado: 'Honduras', pais: 'Honduras', mascote: 'Sol' },
  { nome: 'Southern Soccer Academy', nome_curto: 'SSA', serie: 'INT', cidade: 'Marietta', estado: 'USA', pais: 'Estados Unidos', mascote: 'Southern' },
  { nome: 'St Gallen', nome_curto: 'STG', serie: 'INT', cidade: 'St Gallen', estado: 'Switzerland', pais: 'Suica', mascote: 'Urso' },
  { nome: 'Sampaio Corrêa', nome_curto: 'SAM', serie: 'B', cidade: 'São Luís', estado: 'MA', pais: 'Brasil', mascote: 'Bolívia' },
  { nome: 'Stade Rennais', nome_curto: 'REN', serie: 'INT', cidade: 'Rennes', estado: 'Franca', pais: 'Franca', mascote: 'Ermine' },
  { nome: 'Talleres', nome_curto: 'TAL', serie: 'INT', cidade: 'Cordoba', estado: 'Argentina', pais: 'Argentina', mascote: 'Matador' },
  { nome: 'Tampa Bay Rowdies', nome_curto: 'TAM', serie: 'INT', cidade: 'Tampa', estado: 'USA', pais: 'Estados Unidos', mascote: 'Rowdie' },
  { nome: 'Tanta SC', nome_curto: 'TAN', serie: 'INT', cidade: 'Tanta', estado: 'Egypt', pais: 'Egito', mascote: 'Tanta' },
  { nome: 'Tottenham Hotspur', nome_curto: 'TOT', serie: 'INT', cidade: 'Londres', estado: 'Londres', pais: 'Inglaterra', mascote: 'Chirpy' },
  { nome: 'Tunisia National Team', nome_curto: 'TUN', serie: 'SEL', cidade: 'Tunis', estado: 'Tunisia', pais: 'Tunisia', mascote: 'Águias de Cartago' },
  { nome: 'Union de Santa Fe', nome_curto: 'UNI', serie: 'INT', cidade: 'Santa Fe', estado: 'Santa Fe', pais: 'Argentina', mascote: 'Tatengue' },
  { nome: 'Universidad Cesar Vallejo', nome_curto: 'UCV', serie: 'INT', cidade: 'Trujillo', estado: 'Peru', pais: 'Peru', mascote: 'Poeta' },
  { nome: 'Uruguay National Team', nome_curto: 'URU', serie: 'SEL', cidade: 'Montevideo', estado: 'Uruguay', pais: 'Paraguai', mascote: 'Garra Charrúa' },
  { nome: 'Valencia', nome_curto: 'VAL', serie: 'INT', cidade: 'Valencia', estado: 'Spain', pais: 'Espanha', mascote: 'Morcego' },
  { nome: 'Vasco', nome_curto: 'VAS', serie: 'A', cidade: 'Rio de Janeiro', estado: 'RJ', pais: 'Brasil', mascote: 'Almirante' },
  { nome: 'Vila Nova', nome_curto: 'VIL', serie: 'B', cidade: 'Goiania', estado: 'GO', pais: 'Brasil', mascote: 'Tigrão' },
  { nome: 'Vitoria de Guimaraes', nome_curto: 'VIT', serie: 'INT', cidade: 'Guimaraes', estado: 'Portugal', pais: 'Portugal', mascote: 'Conquistador' },
  { nome: 'Vitoria', nome_curto: 'VIT', serie: 'A', cidade: 'Salvador', estado: 'BA', pais: 'Brasil', mascote: 'Leão' },
  { nome: 'Vorskla Poltava', nome_curto: 'VOR', serie: 'INT', cidade: 'Poltava', estado: 'Ukraine', pais: 'Ucrania', mascote: 'Vorsklo' },
  { nome: 'Wadi Degla', nome_curto: 'WAD', serie: 'INT', cidade: 'Cairo', estado: 'Egypt', pais: 'Egito', mascote: 'Degla' },
  { nome: 'Willem II', nome_curto: 'WIL', serie: 'INT', cidade: 'Tilburg', estado: 'Netherlands', pais: 'Holanda', mascote: 'King Willem' },
  { nome: 'Wolfsburg', nome_curto: 'WOL', serie: 'INT', cidade: 'Wolfsburg', estado: 'Baixa Saxonia', pais: 'Alemanha', mascote: 'Wölfi' }
];

export const CLUBES: ClubData[] = RAW_CLUBS.map(club => ({
  ...club,
  logoUrl: getLogoUrl(club.nome, club.cidade, club.estado, club.pais)
}));

// Adicione isto ao final do arquivo para exportar a constante que o sistema de busca utiliza
export const CLUBS_DATA: ClubData[] = RAW_CLUBS.map((c) => ({
  ...c,
  logoUrl: getLogoUrl(c.nome, c.cidade, c.estado, c.pais),
}));