// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-clubs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
var cached = null;
function getSupabase() {
  if (cached) return cached;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  cached = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  return cached;
}

// src/lib/mcp/tools/search-clubs.ts
var search_clubs_default = defineTool({
  name: "search_clubs",
  title: "Search football clubs",
  description: "Search the Heart Club catalog of football clubs by name. Returns basic identity (name, city, country, mascot, colors, stadium).",
  inputSchema: {
    query: z.string().min(1).describe("Club name or fragment, e.g. 'Flamengo' or 'Real Madrid'."),
    limit: z.number().int().min(1).max(25).optional().describe("Maximum results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = getSupabase();
    const { data, error } = await supabase.from("clubes_cache").select("id,nome,nome_curto,pais,cidade,mascote,cor_primaria,cor_secundaria,escudo_url,estadio_nome,fundado").ilike("nome", `%${query}%`).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clubs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-club-ranking.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_club_ranking_default = defineTool2({
  name: "get_club_ranking",
  title: "Get Heart Club ranking",
  description: "Return the top football clubs on Heart Club ranked by original vote count. Optionally filter by country or city.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many clubs to return (default 10)."),
    country: z2.string().optional().describe("Optional country filter, e.g. 'Brasil'."),
    city: z2.string().optional().describe("Optional city filter, e.g. 'S\xE3o Paulo'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, country, city }) => {
    const supabase = getSupabase();
    let q = supabase.from("votos").select("clube_nome, voto_pais, voto_cidade", { count: "exact" }).eq("is_original_vote", true);
    if (country) q = q.ilike("voto_pais", country);
    if (city) q = q.ilike("voto_cidade", city);
    const { data, error } = await q.limit(5e3);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const name = row.clube_nome;
      if (!name) continue;
      counts.set(name, (counts.get(name) ?? 0) + 1);
    }
    const ranking = [...counts.entries()].map(([clube, votos]) => ({ clube, votos })).sort((a, b) => b.votos - a.votos).slice(0, limit ?? 10);
    return {
      content: [{ type: "text", text: JSON.stringify(ranking, null, 2) }],
      structuredContent: { ranking, filters: { country, city } }
    };
  }
});

// src/lib/mcp/tools/get-census-stats.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_census_stats_default = defineTool3({
  name: "get_census_stats",
  title: "Get census stats",
  description: "Return aggregate Heart Club census statistics: total original votes, distinct clubs, and top countries.",
  inputSchema: {
    club: z3.string().optional().describe("Optional club name to scope the stats to a single club.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ club }) => {
    const supabase = getSupabase();
    let base = supabase.from("votos").select("clube_nome, voto_pais", { count: "exact" }).eq("is_original_vote", true);
    if (club) base = base.ilike("clube_nome", club);
    const { data, count, error } = await base.limit(5e3);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const clubes = /* @__PURE__ */ new Set();
    const paises = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const r = row;
      if (r.clube_nome) clubes.add(r.clube_nome);
      if (r.voto_pais) paises.set(r.voto_pais, (paises.get(r.voto_pais) ?? 0) + 1);
    }
    const topCountries = [...paises.entries()].map(([pais, votos]) => ({ pais, votos })).sort((a, b) => b.votos - a.votos).slice(0, 10);
    const stats = {
      total_original_votes: count ?? data?.length ?? 0,
      distinct_clubs: clubes.size,
      top_countries: topCountries,
      scoped_to: club ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "heart-club-mcp",
  title: "Heart Club MCP",
  version: "0.1.0",
  instructions: "Tools for the Heart Club football census platform. Use `search_clubs` to find a club, `get_club_ranking` for the Voto Sagrado leaderboard, and `get_census_stats` for aggregate statistics. All tools are read-only and expose public data only (no personal information).",
  tools: [search_clubs_default, get_club_ranking_default, get_census_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
